### PR TITLE
Prevent infinite loop when calling foreach after deleting head

### PR DESCRIPTION
**Pull request by szogun1987**
### Please provide enough information so that others can review your pull request
- What does this implement/fix? Explain your changes.
- Does this close any currently open issues?
It is related to https://github.com/jaredLunde/react-hook/issues/193uh
Solution contains unit test.

- Include the package name or names you're updating in your PR title, e.g. `[async] Fixes #129`, `[debounce, throttle] Updates build scripts` 
Nothing but internal implementation

### Testing

Confirm that your pull request contains tests and that all existing tests pass.
They do

### CODE REVIEW

**Comment by szogun1987** [comment]
Closes #193

**Comment by szogun1987** [comment]
@jaredLunde Could you accept this PR?

Additional explanation why code worked improperly:

1. Write method adds 1st element and sets head to it.
2. Write method adds 2nd element and sets head to it.
3. Delete methods removes 2nd element, sets it's next and prev field to itself but, left head set to it.
4. foreach method starts with 1st element (head's next), but it never get's to 2nd one (set as head) as 1st element has next and prev set to itself.

**Comment by jaredLunde** [comment]
Thanks!

**Comment by szogun1987** [comment]
Great thank you.

**Comment by jaredLunde** [comment]
👍🏻 in `1.1.1`

**Pull request merged**
